import type { Metadata } from 'next'
import { Home, TrendingUp, ShieldCheck } from 'lucide-react'
import CTABox from '@/components/CTABox/CTABox'
import s from './page.module.css'

export const metadata: Metadata = { title: 'Why Aspire — Aspire REIT' }

export default function WhyAspirePage() {
  return (
    <>
      <section className={s.pageHero}>
        <div className={`wrap ${s.heroInner}`}>
          <span className={`eyebrow ${s.eyebrow}`}>Why Aspire</span>
          <h1>Built for families and investors alike</h1>
          <p>
            Aspire is a residential REIT with a clear mandate: deliver quality, affordable homes to
            Ghanaian families and turn the rental income they generate into durable,
            inflation-beating returns for investors.
          </p>
        </div>
      </section>

      <section className="bg-light">
        <div className="wrap sec-pad">
          <div className={s.secHead}>
            <span className="eyebrow">Our approach</span>
            <h2>Three things we get right</h2>
          </div>
          <div className={s.pillars}>
            <article className={s.pillar}>
              <div className={s.ico}><Home size={22} /></div>
              <h3>Affordable by design</h3>
              <p>Well-built 2–4 bedroom homes — semi-detached, terraced and apartments — priced within reach of Ghanaian families, in connected locations like Achimota.</p>
            </article>
            <article className={s.pillar}>
              <div className={s.ico}><TrendingUp size={22} /></div>
              <h3>Income that beats inflation</h3>
              <p>A real yield of over 9%, generated by rental income from homes people genuinely want to live in — not speculation.</p>
            </article>
            <article className={s.pillar}>
              <div className={s.ico}><ShieldCheck size={22} /></div>
              <h3>Transparent and SEC-registered</h3>
              <p>Professionally managed and SEC-registered in Ghana, aligning the interests of homeowners and investors through clear reporting and disciplined governance.</p>
            </article>
          </div>
          <div className={s.statsRow}>
            <div className={s.statCard}>
              <div className={s.num}>9%+</div>
              <div className={s.lab}>Real yield to investors, generated by rental income</div>
            </div>
            <div className={s.statCard}>
              <div className={s.num}>100%</div>
              <div className={s.lab}>Phase 1 homes fully subscribed</div>
            </div>
            <div className={s.statCard}>
              <div className={s.num}>2–4 bed</div>
              <div className={s.lab}>Home types — built for Ghanaian families</div>
            </div>
          </div>
        </div>
      </section>

      <section className="bg-light">
        <div className="wrap" style={{ paddingBottom: '96px' }}>
          <CTABox />
        </div>
      </section>
    </>
  )
}
