import type { Metadata } from 'next'
import CTABox from '@/components/CTABox/CTABox'
import s from './page.module.css'

export const metadata: Metadata = { title: 'Invest — Aspire REIT' }

export default function InvestPage() {
  return (
    <>
      <section className={s.pageHero}>
        <div className={`wrap ${s.heroInner}`}>
          <span className={`eyebrow ${s.eyebrow}`}>Invest</span>
          <h1>Real returns from real homes</h1>
          <p>
            Aspire REIT offers Ghanaian and diaspora investors a straightforward way to earn
            income from residential property — without the hassle of direct ownership.
          </p>
        </div>
      </section>

      <section className="bg-light">
        <div className="wrap sec-pad">
          <div className={s.secHead}>
            <span className="eyebrow">How it works</span>
            <h2>Three simple steps</h2>
          </div>
          <div className={s.steps}>
            <div className={s.step}>
              <div className={s.stepNum}>1</div>
              <h3>Join the waitlist</h3>
              <p>Register your interest and receive the investor prospectus when Phase 2 opens.</p>
            </div>
            <div className={s.step}>
              <div className={s.stepNum}>2</div>
              <h3>Review the prospectus</h3>
              <p>Read the SEC-registered offering document, review the financials, and decide your allocation.</p>
            </div>
            <div className={s.step}>
              <div className={s.stepNum}>3</div>
              <h3>Receive income</h3>
              <p>Earn quarterly distributions from rental income generated by the portfolio — target yield 9%+.</p>
            </div>
          </div>

          <div className={s.factsGrid}>
            <div className={s.factRow}><span className={s.factLabel}>Target yield</span><span className={s.factVal}>9%+ per annum (real)</span></div>
            <div className={s.factRow}><span className={s.factLabel}>Structure</span><span className={s.factVal}>SEC-registered REIT (Ghana)</span></div>
            <div className={s.factRow}><span className={s.factLabel}>Asset type</span><span className={s.factVal}>Residential — 2–4 bed homes</span></div>
            <div className={s.factRow}><span className={s.factLabel}>Fund manager</span><span className={s.factVal}>10th Capital Investments</span></div>
            <div className={s.factRow}><span className={s.factLabel}>Phase 1 status</span><span className={s.factVal}>Fully subscribed</span></div>
            <div className={s.factRow}><span className={s.factLabel}>Contact</span><span className={s.factVal}>info@aspirereit.fund</span></div>
          </div>

          <p className={s.disclaimer}>
            Capital at risk. The value of investments and the income from them can fall as well as rise.
            Past performance is not a reliable indicator of future results. This is not financial advice.
          </p>
        </div>
      </section>

      <section className="bg-light">
        <div className="wrap" style={{ paddingBottom: '96px' }}>
          <CTABox />
        </div>
      </section>
    </>
  )
}
